public class ReportPrinter {

    // Constant line separator
    private static final String LINE =
            "==============================================";

    // Method to print header
    public void printHeader() {
        System.out.println(LINE);
        System.out.println(" STUDENT GRADE TRACKER REPORT");
        System.out.println(LINE);

        System.out.printf("%-5s %-12s %8s %6s %8s%n",
                "Roll", "Name", "Average", "Grade", "Result");

        System.out.println("----------------------------------------------");
    }

    // Method to print each student's report
    public void printStudentReport(Student s, double avg,
                                   String letter, boolean pass) {

        System.out.printf("%-5d %-12s %8.2f %6s %8s%n",
                s.getRollNumber(),
                s.getName(),
                avg,
                letter,
                pass ? "PASS" : "FAIL");
    }

    // Method to print footer
    public void printFooter(int totalStudents) {
        System.out.println(LINE);
        System.out.println("Total students processed: " + totalStudents);
        System.out.println("Report generated by: Student Grade Tracker v1.0");
        System.out.println(LINE);
    }
}
